version: '3.8'
services:
  db:
   image: postgres:15
   container_name : organize-simple-db
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: true
     POSTGRES_DB: organize-simple
   ports:
     - '5433:5432'
   volumes:
     - db-data:/var/lib/postgresql/data
volumes:
  db-data:
   name: organize-simple-data

